### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'Dataset'

### ISSUE THREAD

**Issue by MHassaanButt** [zilongzhong/SSTN#8]
When I am trying to run est_IN.py I got this error:

Traceback (most recent call last):
  File "test_IN.py", line 263, in <module>
    class HSIDataset(data.Dataset):
AttributeError: 'numpy.ndarray' object has no attribute 'Dataset'

Could anybody help me with this issue and how to fix it?

Thanks!

**Comment by zilongzhong** [comment]
Maybe you can just replace data.Dataset with torch.utils.data.Dataset, It
seems data is overloaded as a NumPy array.

**Comment by MHassaanButt** [comment]
Thank you so much for your kind response. Yes, it's work.
